// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://telslaeykvfpmcrrnprb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlbHNsYWV5a3ZmcG1jcnJucHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDgwMTcsImV4cCI6MjA2MjgyNDAxN30.V6jurIAi630RJk2KIN901h_CJl69RLfbtjQbt6kcNUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);